-- MySQL Script generated by MySQL Workbench
-- Tue Sep 19 14:40:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema restful_friendsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restful_friendsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restful_friendsdb` DEFAULT CHARACTER SET utf8 ;
USE `restful_friendsdb` ;

-- -----------------------------------------------------
-- Table `restful_friendsdb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restful_friendsdb`.`table1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(225) NULL,
  `lname` VARCHAR(225) NULL,
  `email` VARCHAR(250) NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
