-- MySQL Script generated by MySQL Workbench
-- Fri Sep 15 11:42:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema loginregdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loginregdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loginregdb` DEFAULT CHARACTER SET utf8 ;
USE `loginregdb` ;

-- -----------------------------------------------------
-- Table `loginregdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loginregdb`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `address` VARCHAR(225) NOT NULL,
  `password` VARCHAR(225) NOT NULL,
  `time_created` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
